#!/usr/bin/env python3
# Generate the glue between Apple's GL dispatch table and Mesa.
#
#   gen_dispatch.py <gliDispatch.h> <output.c>
#
# Apple's public header (in the 10.4u SDK) declares the table as a structure
# of function pointers, each taking the engine's context first:
#     void (*clear_color)(GLIContext ctx, GLclampf red, ...);
# For every entry whose OpenGL function Mesa has (clear_color is
# glClearColor), this writes a function with the table's signature that
# makes the right Mesa context current and calls Mesa's, plus the code that
# looks Mesa's functions up and puts ours in a table. The output is built
# from Apple's header at build time and is not kept in the repository.
#
# Copyright (c) 2026 kouta-kun and Claude
# SPDX-License-Identifier: MIT

import re
import sys

ENTRY = re.compile(r'^\s*(.+?)\(\*\s*([A-Za-z0-9_]+)\s*\)\s*\(\s*GLIContext\s+ctx\s*(?:,\s*(.*?))?\)\s*;', re.S)


def gl_name(entry):
    """clear_color -> glClearColor, tex_image2D -> glTexImage2D."""
    return 'gl' + ''.join(p[:1].upper() + p[1:] for p in entry.split('_'))


def arg_names(params):
    names = []
    for p in params.split(','):
        m = re.search(r'([A-Za-z_][A-Za-z0-9_]*)\s*(?:\[[^\]]*\])?\s*$', p)
        if not m:
            return None
        names.append(m.group(1))
    return names


def trace_call(name, params, names):
    """The rdn_log call that prints one GL call with its arguments."""
    fmt, args = [], []
    for p, n in zip(params.split(',') if params else [], names):
        if '*' in p or '[' in p:
            fmt.append('%p')
            args.append('(void *)%s' % n)
        elif re.search(r'GL(float|clampf|double|clampd)\b', p):
            fmt.append('%g')
            args.append('(double)%s' % n)
        else:
            fmt.append('0x%lx')
            args.append('(unsigned long)%s' % n)
    return 'rdn_log("%s(%s)"%s)' % (gl_name(name), ', '.join(fmt),
                                    ''.join(', ' + a for a in args))


def main():
    text = open(sys.argv[1]).read()
    body = text[text.index('__GLIFunctionDispatchRec'):]
    body = body[body.index('{') + 1:body.index('}')]
    entries = []
    for decl in body.split(';'):
        m = ENTRY.match(decl + ';')
        if not m:
            continue
        ret, name, params = m.group(1).strip(), m.group(2), (m.group(3) or '').strip()
        names = arg_names(params) if params else []
        if names is None:
            continue
        entries.append((ret, name, params, names))

    out = ['/* Generated by gen_dispatch.py from the SDK\'s gliDispatch.h. */',
           '#include "rdn_dispatch.h"', '']
    for ret, name, params, names in entries:
        mesa_params = params if params else 'void'
        full = 'GLIContext ctx' + (', ' + params if params else '')
        call = 'm_%s(%s)' % (name, ', '.join(names))
        out.append('static %s (*m_%s)(%s);' % (ret, name, mesa_params))
        out.append('static %s t_%s(%s)' % (ret, name, full))
        out.append('{')
        out.append('\tRDN_ENTER(ctx);')
        out.append('\tif (__builtin_expect(rdn_trace, 0))')
        out.append('\t\t%s;' % trace_call(name, params, names))
        out.append('\t%s%s;' % ('' if ret == 'void' else 'return ', call))
        out.append('}')
        out.append('')

    out.append('static const struct { const char *name; void **mesa; } lookups[] = {')
    for ret, name, params, names in entries:
        out.append('\t{ "%s", (void **)&m_%s },' % (gl_name(name), name))
    out.append('};')
    out.append('')
    out.append('unsigned rdn_dispatch_resolve(void *(*lookup)(const char *name),')
    out.append('\t\t\t      void (*missing)(const char *name))')
    out.append('{')
    out.append('\tunsigned i, found = 0;')
    out.append('')
    out.append('\tfor (i = 0; i < sizeof(lookups) / sizeof(lookups[0]); i++) {')
    out.append('\t\t*lookups[i].mesa = lookup(lookups[i].name);')
    out.append('\t\tif (*lookups[i].mesa)')
    out.append('\t\t\tfound++;')
    out.append('\t\telse if (missing)')
    out.append('\t\t\tmissing(lookups[i].name);')
    out.append('\t}')
    out.append('\treturn found;')
    out.append('}')
    out.append('')
    out.append('#include <stddef.h>')
    out.append('#define FITS(field) (offsetof(GLIFunctionDispatch, field) / sizeof(void *) < entries)')
    out.append('')
    out.append('unsigned rdn_dispatch_install(void *table, unsigned entries)')
    out.append('{')
    out.append('\tGLIFunctionDispatch *disp = table;')
    out.append('\tunsigned n = 0;')
    out.append('')
    for ret, name, params, names in entries:
        out.append('\tif (m_%s && FITS(%s)) { disp->%s = t_%s; n++; }' % (name, name, name, name))
    out.append('\treturn n;')
    out.append('}')
    out.append('')
    out.append('const unsigned rdn_dispatch_entries = %d;' % len(entries))
    open(sys.argv[2], 'w').write('\n'.join(out) + '\n')


if __name__ == '__main__':
    main()
