#!/usr/bin/env python3
"""Compatibility list: validate data/compat/*.toml and render docs/COMPAT.md.

  scripts/compat.py render     write docs/COMPAT.md
  scripts/compat.py check      validate the data; fail if docs/COMPAT.md is stale

Standard library only (Python 3.11+ for tomllib). Every report is something
the user looked at on the card's monitor; the schema is in
data/compat/README.md.
"""
import sys, tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "compat"
OUT = ROOT / "docs" / "COMPAT.md"

TIERS = ["perfect", "playable", "glitches", "menu", "broken", "unrated"]
TIER_TEXT = {
    "perfect": "Perfect", "playable": "Playable", "glitches": "Glitches",
    "menu": "Menu only", "broken": "Does not run", "unrated": "Not rated",
}
REQUIRED_GAME = ["name", "year"]
REQUIRED_REPORT = ["date", "tier"]
KNOWN_REPORT = {
    "date", "tier", "version", "driver", "gpu", "machine", "resolution", "mode",
    "fps", "baseline_fps", "settings", "repro", "switches", "issues", "notes",
    "reporter",
}
KNOWN_GAME = {"name", "publisher", "year", "engine", "api", "report"}


def load():
    games, errors = [], []
    for p in sorted(DATA.glob("*.toml")):
        try:
            g = tomllib.loads(p.read_text())
        except tomllib.TOMLDecodeError as e:
            errors.append(f"{p.name}: {e}")
            continue
        g["_slug"] = p.stem
        for k in REQUIRED_GAME:
            if k not in g:
                errors.append(f"{p.name}: missing '{k}'")
        for k in set(g) - KNOWN_GAME - {"_slug"}:
            errors.append(f"{p.name}: unknown key '{k}'")
        reports = g.get("report", [])
        if not reports:
            errors.append(f"{p.name}: no [[report]]")
        for i, r in enumerate(reports):
            where = f"{p.name} report {i + 1}"
            for k in REQUIRED_REPORT:
                if k not in r:
                    errors.append(f"{where}: missing '{k}'")
            if r.get("tier") not in TIERS:
                errors.append(f"{where}: tier must be one of {', '.join(TIERS)}")
            for k in set(r) - KNOWN_REPORT:
                errors.append(f"{where}: unknown key '{k}'")
        g["report"] = sorted(reports, key=lambda r: str(r.get("date", "")),
                             reverse=True)
        games.append(g)
    return games, errors


def cell(s):
    return str(s).replace("|", "\\|").replace("\n", " ")


def fps_text(r):
    if "fps" not in r:
        return ""
    s = f"{r['fps']:g}"
    b = r.get("baseline_fps")
    if b:
        s += f" (6600 LE {b:g})"
    return s


def render(games):
    out = [
        "<!-- Generated by scripts/compat.py from data/compat/*.toml. Do not edit. -->",
        "# Compatibility list",
        "",
        "Games of the Mac OS X 10.4 era on the Radeon HD 7570 in a Power Mac G5,",
        "Tiger 10.4.11. Every entry was looked at on the card's monitor.",
        "How to read it and how to report: `data/compat/README.md`.",
        "",
        "| Game | Tier | Version | Resolution | fps | Needs | Notes |",
        "|---|---|---|---|---|---|---|",
    ]
    counts = {t: 0 for t in TIERS}
    for g in sorted(games, key=lambda g: g["name"].lower()):
        r = g["report"][0]
        counts[r["tier"]] += 1
        needs = ", ".join(r.get("switches", []))
        out.append("| " + " | ".join(cell(x) for x in (
            g["name"], TIER_TEXT[r["tier"]], r.get("version", ""),
            r.get("resolution", ""), fps_text(r), needs, r.get("notes", ""),
        )) + " |")
    out += ["", "Tiers: " + ", ".join(
        f"{TIER_TEXT[t]} {counts[t]}" for t in TIERS if counts[t]), ""]
    out += ["## Details", ""]
    for g in sorted(games, key=lambda g: g["name"].lower()):
        out.append(f"### {g['name']}")
        meta = [str(g.get(k)) for k in ("publisher", "year", "engine") if g.get(k)]
        out.append(" · ".join(meta))
        if g.get("api"):
            out.append("")
            out.append("API: " + ", ".join(g["api"]))
        for r in g["report"]:
            out += ["", f"**{r['date']}: {TIER_TEXT[r['tier']]}**"]
            for k, label in (("driver", "Driver"), ("gpu", "Card"),
                             ("machine", "Machine"), ("mode", "Mode"),
                             ("settings", "Settings"), ("repro", "Reproduce"),
                             ("reporter", "Reported by")):
                if r.get(k):
                    out.append(f"- {label}: {r[k]}")
            for i in r.get("issues", []):
                out.append(f"- Issue: {i}")
        out.append("")
    return "\n".join(out)


def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else "render"
    games, errors = load()
    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1
    text = render(games)
    if cmd == "render":
        OUT.write_text(text)
        print(f"{OUT.relative_to(ROOT)}: {len(games)} games")
        return 0
    if cmd == "check":
        if not OUT.exists() or OUT.read_text() != text:
            print("docs/COMPAT.md is stale: run scripts/compat.py render",
                  file=sys.stderr)
            return 1
        print(f"ok, {len(games)} games")
        return 0
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main())
